### ISSUE TITLE
Sharing A stream among WebRTC Clients

### ISSUE THREAD

**Issue by eslam-ahmed-khair** [WebRTSP/ReStreamer#6]
Hello,

I was just curious to know if it is possible to share the same `webrtcbin` among multiple clients. and if that's not possible then share the `uridecodebin` among multiple `webrtcbin` belonging to different clients.

I asked this because for every client, the stream is pulled again increasing the bandwidth.

Thanks in advance,
Best Regards.

**Comment by RSATom** [comment]
It's not possible to share the same `webrtcbin` among multiple clients, just because `webrtcbin` instance can negotiate connection parameters (ICE) and encryption keys only with single client. It's by design.
But it's possible to share the same streaming pipeline among multiple `webrtcbin` instances. Here is example: https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc/multiparty-sendrecv/gst
And right now I'm working on implementing this approach in WebRTSP project.

**Comment by eslam-ahmed-khair** [comment]
Great, Thank you!
